### PR TITLE
Math magicians: full website

### PR DESCRIPTION
**Pull request by jojo987N**
###  Math magicians: full website
For this milestone :

- Created a website consisting of 3 pages: Home, Calculator, and Quote.
- The general layout match wireframes
- Used React basic styling
- Every page, has a Route.
- Navigation links for all 3 routes are displayed on each page.
- Used React Router to make the routes work.
- Checked that there are no linter errors
- Used correct Gitflow

### CODE REVIEW

**Review by FrederickMih — COMMENTED** [review]
## Hi :raising_hand: :raising_hand: @jojo987N, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Let's kindly get rid of all headers in the README.md file that do not apply to this project. For example, you should have removed the Live Demo and Deployment headers since the app is not yet deployed. Please do not modify the original [README template](https://github.com/microverseinc/readme-template/edit/master/README.md). The `Table of Contents` of your README file is a bit modify.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jojo987N** [comment]
Is this a serious review in a react project?! yet my readme file is clear to understand!

**Comment by FrederickMih** [comment]
> Is this a serious review in a react project?! yet my readme file is clear to understand!

@jojo987N, this is not a review. It's one reason why the project should be invalidated. You need to remove unnecessary headers in the READMEf file instead of adding the text "coming soon". If you deploy your project then the Live Demo header is necessary.

**Comment by jojo987N** [comment]
Yet my readme file is clear to understand!

**Comment by FrederickMih** [comment]
> Yet my readme file is clear to understand!

NB. I'm not talking about clarity. I'm talking of reasons for invalidation.

**Review by mikethreels — APPROVED** [review]
Hi Jemba, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job creating the full webpage
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
